source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CommonAlertFramework_Example', :exclusive => true do
  pod "CommonAlertFramework", :path => "../"
end

target 'CommonAlertFramework_Tests', :exclusive => true do
  pod "CommonAlertFramework", :path => "../"

  pod 'FBSnapshotTestCase'
end
